Sprint3 refactor other info window
elagarrigue/AyDS21-JK-Hera2 pull request #2
Opened 2021-05-11 00:05 UTC by lucasch98

Refactor del modulo MoreDetails.

2021-05-14 12:42 UTC, elagarrigue requested changes
Muy bien encaminado

2021-05-14 12:42 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        abstractText.maximumSize = Dimension(600, 400)
Constantes

2021-05-14 12:42 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        viewFullArticlePanel.maximumSize = Dimension(600, 12)
Constantes

2021-05-14 12:42 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun displayArtistInfo() {
El nombre no es correcto, es parte del algoritmo repository y no hace el display en sí

2021-05-14 12:49 UTC, elagarrigue commented
@GiannFrancoo , no aparecen commits tuyos, aparecen anónimos. Fijate de configurar los datos de los commits en el git local (ya sea por consola o en la herramienta GUI)

2021-05-14 14:54 UTC, GiannFrancoo commented
> o

Si! los commits que fueron anonimos fueron mios! tenia mal puesto el mail en la configuración del github desktop! gracias por avisarme!

2021-05-17 12:06 UTC, elagarrigue requested changes

2021-05-17 12:06 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                getInfoArtistNameFromAbstract()
nivel de abst., un paso

2021-05-17 12:06 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }
codigo duplicado

2021-05-18 13:25 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoSqlDBImpl.kt
> +    private fun getInfoWithArtist(artist:String):String? {
No quedó bien indentada la clase

2021-05-18 13:45 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
Esto es incorrecto. addHyperlinkListener se refiere a los hipervínculos dentro del html. Al hacer `openExternalUrl()` están abriendo la url del artículo. Revisen el código original.

2021-05-19 17:12 UTC, elagarrigue approved these changes
Excelente

2021-05-19 17:12 UTC, merged