Sprint4 refactor de arquitectura
elagarrigue/AyDS21-JK-Hera2 pull request #3
Opened 2021-05-26 20:26 UTC by RinghettiFranco

Tuvimos un problema con el observer: al abrir un moredetails nuevo, y solicitar ver el articulo completo se creaba un nuevo suscriber. Para solucionarlo implementamos una condición que al ya haber una suscripción, no la genera. Creemos que no es una solución "ideal" pero nos gustaría que nos den su opinión respecto a su correctitud. 

Pensamos dos alternativas posibles que son:
+ Implementar un singleton para asegurarnos que haya un único observer.
+ Capturar el cierre de ventana y en ese momento cancelar la suscripcion.

2021-05-27 13:50 UTC, elagarrigue requested changes
Excelente! Pocos errores blockeantes.

Además:
- resources debería contener sólo recursos del sistema, no documentación (se meten en el compilable). Sacar a la raíz del repositorio, en una carpeta docs
- Diagrama de clases:
    - no veo los paquetes, sólo clases
    - debería estar simplificado, sólo interfaces, sin los inyectores

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/home/controller/HomeController.kt
> +        MoreDetailsViewModule.moreDetailsView.openView(song)
- Inicializar el módulo de more details desde home controller no es lo ideal. Siempre que sea posible, tenemos que tratar de evitar referenciar a los inyectores, que la dependencia sea al revés.  O sea, en vez de inyectar `moreDetailsControllerModule`, inyectar more details controller (y en ese caso, `song`  va a ser una propiedad del controller).
- Home controller  no debería conocer a la view de more details, es responsabilidad de more details controller.

Resumen: En esta clase deberíamos:
- Inyectar More Details Controller 
- en moreDetails action, ejecutar moreDetailsController.open(song)

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +    private val song: Song
Eliminar propiedad song, crear método `open(song)`

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/NYTimesAPI.kt
> +/*
Eliminar dead code

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +/*
Eliminar dead code

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/home/view/HomeUiWindowComponents.kt
> +
Revertir cambios

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +private var alreadySubscribe : Boolean = true
Definitivamente un smell

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +            alreadySubscribe = false
Esto no tiene que hacer falta. El problema parece ser el grafo de instancias. Están crean cada vez una instancia del controller, pero de la view tienen siempre una sola instancia. Sacando song como propiedad del controller y creándolo una sola vez se debería solucionar el problema.

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +        moreDetailsModel.searchArticle(song.artistName)
open(song)

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/controller/MoreDetailsController.kt
> +        navigationUtils.openExternalUrl(moreDetailsView.uiState.articleUrl)
Si bien no está mal que el controller acceda al estado de la view, se puede simplificar y a la vez generalizar haciendo que el evento de ui sea más genérico,  MoreDetailsUiEvent.OpenUrl(url) en vez de  MoreDetailsUiEvent.ViewFullArticle.
```
private fun openExternalUrl(url: String) {        
  navigationUtils.openExternalUrl(url)

```

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
> +    //fun getSongById(id: String): Song
Eliminar código comentado

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
> +    //override fun getSongById(id: String): Song = repository.getSongById(id)
código comentado

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/entities/NYTArticle.kt
> +    val articleSource: Int
En esta etapa no se utiliza source, sólo en la DB. Mejor eliminarlo.

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/external/nytimes/article/NYTArticleModule.kt
> +    val NYTArticleService: NYTArticleService = NYTArticleServiceImpl(
propiedades siempre en camelCase

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/external/nytimes/article/NYTToArticleResolver.kt
> +                    -1, //ArticleSource
Al eliminar la propiedad, se elimina este smell

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/external/nytimes/article/NYTToArticleResolver.kt
> +            var abstract = cleanEnterOfAbstract(it.toString())
puede ser val

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/external/nytimes/article/NYTToArticleResolver.kt
> +        return response
se puede hacer inline, no hace falta la variable temporal

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/external/nytimes/article/NYTToArticleResolver.kt
> +            return abstract
se puede hacer inline, no hace falta la variable temporal

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/nytimes/sqldb/NYTSqlQueries.kt
> +    override fun getInsertArticleQuery(artistName: String, article: NYTArticle): String =
Es buena práctica utilizar los mismos nombres de parámetros en las funciones que se sobre escriben

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/ArticleDescriptionHelper.kt
> +        val locallyStoraged = if (article.isLocallyStoraged) LOCAL_MARK else ""
Esta sentencia no tiene el mismo nivel de abstracción que las otras, mover a sub función

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/ArticleDescriptionHelper.kt
> +        .replace("(?i)" + artistName.toRegex(), "<b>" + artistName.toUpperCase() + "</b>")
otro nivel de abstracción

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/ArticleDescriptionHelper.kt
> +        return builder.toString()
Se puede simplificar: 
```suggestion
        return StringBuilder().apply {
           append("<html><div width=400 >")
           append("<font face=\"arial\">")
           append(locallyStoraged())
           append(articleData() )         
           append("</font></div></html>")
        }.toString()       
```

2021-05-27 13:50 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +    private var artistName = ""
Debería ser parte del uiState

2021-06-03 12:41 UTC, elagarrigue requested changes
Un último detalle muy chico, y falta actualizar la descripción del PR

2021-06-03 12:41 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +    private val moreDetailsModel:ayds.hera.songinfo.moredetails.model.MoreDetailsModel,
Hacer el import para evitar en namespace en la declaración de la propiedad. Además, falta un espacio después de `:`

2021-06-03 15:32 UTC, CarolinaSiracusa commented
Se modificó la estructura del paquete moredetails para llevarlo a una arquitectura Modelo-Vista-Controlador respetando SOLID y clean code, el grupo se dividio en dos subgrupos:
Gian y Franco a cargo del diseño del modelo
Lucas y Caro a cargo de la vista y el controlador 

Se diseño un diagrama de clases (sin atributos ni métodos) que se ubica en la carpeta docs.

2021-06-03 15:33 UTC, elagarrigue approved these changes

2021-06-03 15:33 UTC, merged