Sprint5 abstraccion servicio externo
elagarrigue/AyDS21-JK-Hera2 pull request #4
Opened 2021-06-19 14:53 UTC by RinghettiFranco

Este es el link del repositorio del modulo externo: https://github.com/GiannFrancoo/AK-Hera2-NYTimesData
En este momento es privado, esperamos al lunes porque no sabemos como quieren que lo configuremos.

Se realizo la extracción de la lógica y funcionalidad de la API del New York Times del MoreDetails.

2021-06-22 14:37 UTC, elagarrigue reviewed
Me faltó hacer el finish review ayer. Hagan el re request cuando estén listos.

2021-06-23 13:28 UTC, GiannFrancoo commented
- Se modifico el diagrama de clases para que corresponda.
- Se hicieron internals las clases del submódulo solo las que no son necesarias que sean vistas desde el programa principal.
- Se actualizo el readme.md en el repositorio del submódulo y se hizo publico.
 https://github.com/GiannFrancoo/AK-Hera2-NYTimesData
- Se modifico los nombres de las clases del paquete principal para eliminar Article y sea Card.

2021-06-23 15:45 UTC, elagarrigue requested changes
Últimos cambios:

Submodule:
- Readme: agreguen ejemplos de código de cómo obtener la referencia al servicio y cómo obtener la entidad, para que quede  más claro
- Eliminar `EmptyArticle`, no se utiliza
- Tener Article y NYTArticle no suma nada, unificar en una sola clase

Hagan el repo público directamente

2021-06-23 20:18 UTC, elagarrigue approved these changes
Excelente 👍🏽

2021-06-23 20:18 UTC, merged