Sprint-6 Broker y  servicios externos
elagarrigue/AyDS21-JK-Hera2 pull request #5
Opened 2021-07-02 03:05 UTC by CarolinaSiracusa

Se integraron en el proyecto los servicios asignados por la cátedra.
Ambos servicios externos debieron ser modificados para evitar inconsistencias que producían errores.
Se implemento el patrón broker que integra los tres servicios externos, realizando un proxy por cada servicio
Ademas se adaptó la lógica de los estados y de la generación de cards para trabajar con la multiplicidad.
La vista fue modificada de forma tal de visualizar las cards con la información correspondiente de cada servicio que provea datos sobre la búsqueda realizada.

2021-07-02 21:39 UTC, elagarrigue requested changes
- Diagrama:
  - Agregar los proxies específicos, ya que no es 1 a 1 como con otras implementaciones

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModel.kt
> +    fun cardObservable(): Observable<MutableList<Card>>
(Segregación de Interfaces) Exponer una List, no una MutableList

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/MoreDetailsModelModule.kt
> +    private val repository: CardRepository = CardRepositoryImpl(localStorage, broker)
`BrokerModule.broker` como con las otras depedencias, por uniformidad

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +    fun getCardsByArtist(artistName: String): MutableList<Card>
Exponer una Lista no mutable

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
>                  }
El try-catch debería transladarse a los proxy. Si algo falla en un proxy no queremos no devolver los otros resultados

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +                        card.let {
Este let no es necesario

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/CardRepository.kt
> +                        card.let {
Se puede usar `cardList.foreach`

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    private val proxyLastFM: ProxyLastFM
ID: El broker debe depender de interfaces, no clases concretas

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    private var listOfCards : MutableList<Card> = mutableListOf()
No hace falta esta propiedad

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    fun getListOfCards(artistName: String): MutableList<Card>
List

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Broker.kt
> +    }
No es muy clean, se pasan los proxy por parámetro...  Se puede simplificar


```suggestion
    override fun getListOfCards(artistName: String): MutableList<Card> =
      mutableListOf<Card>().apply {
            proxyNYTimes.getCard(artistName)?.let{ add(it) }
            proxyLastFM.getCard(artistName)?.let{ add(it) }
            proxyWikipedia.getCard(artistName)?.let{ add(it) }
        }
```

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/BrokerModule.kt
> +    private val proxyNYTimes : ProxyNYTimes = ProxyNYTimes(nytArticleService)
private val proxyNYTimes : Proxy

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/Proxy.kt
> +
Limpiar estas líneas extra

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyLastFM.kt
> +                    it.sourceLogoURL,
Diferente nivel de abstracción, mover a una función

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyNYTimes.kt
> +                it.sourceLogoUrl,
nivel de abstracción

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyWikipedia.kt
> +        return card
Muchos niveles de abstracción, limpiar

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/local/CardLocalStorage.kt
> +    fun getCardsByArtist(artist: String): MutableList<Card>
List

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiEvent.kt
> +    }
Usar data class, no singleton

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiState.kt
> +class States{
El nombre es poco claro. `MoreDetailsListUiState ` es un poco mas claro. Otra opción es mantener `MoreDetailsUiState `, y cambiar la otra clase a `CardUiState `.

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +            )
Esto no hace nada 🤔

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        var enableButton: Boolean = card is CardImpl
No hace falta que sean variables.  Hay un smell de complejidad acá, se puede resolver más simple me parece (checkeando `card is CardImpl` en `updateUiState`, sin necesidad de pasar el parámetro `enableButton`)

2021-07-02 21:39 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        return cardState
```

return  MoreDetailsUiState(
            description = cardDescriptionHelper.getCardDescriptionText(cardState.artistName, card),
            infoUrl = card.infoUrl,
            sourceLogoUrl = card.sourceLogoUrl,
            actionsEnabled = true
            actionsEnabled = enableButton
        )
```

2021-07-02 23:02 UTC, lucasch98 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiEvent.kt
> +    }
Hola profe, teníamos una consulta no sabemos como aplicar el data class ya que utilizamos el object para determinar el tipo de evento en el controller. Como podríamos igualar este comportamiento con una data class?

2021-07-03 00:06 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsUiEvent.kt
> +    }
En el case  when hacen `is ViewFullCard -> `

2021-07-05 14:45 UTC, GiannFrancoo commented
Las búsquedas que generaron conflictos (Ya solucionados):
- "rfrf": Excepción de wikipediaToResolver (ArrayException: IndexOutOfBoundsException).
- "epor": Ejemplo de mostrar solamente 2 cards.
- "Hoej": Trae solo de Wikipedia.
- "refri" Seguido de cualquier otra canción: Causaba que se abrieran 6 ventanas. (Se sugiere que se busque "The Doors" después de realizar esta búsqueda)

Se modificó el diagrama de clases con las correcciones mencionadas.

2021-07-05 18:13 UTC, elagarrigue requested changes
Diagrama: 
- Las dependencias de los proxies a las libs externas están invertidas

2021-07-06 12:45 UTC, elagarrigue requested changes
Cuando no se encuentran resultados (ninguno de los servicios retorna datos, o no hay conexión), la UI no es clara. Mostrar un mensaje claro, un pop up sería ideal. 
Opcional: si tienen tiempo, alguna indicación de que se están buscando datos sería ideal, tarda mucho en fallar, parece que se congela la app.

Casos de prueba:
- "refri": no pude reproducir el error. Yo creo q tenían un problema en el repository y se solucionó
- "rfrf": Esta claro qué es lo que pasa. Analícenlo y cuéntenlo en la presentación final

2021-07-06 21:00 UTC, CarolinaSiracusa commented
Hola profe!
Estuvimos implementando el PopUp para que muestre un mensaje de busqueda y en caso de no encontrar resultados que asi lo indique.
Pero notamos que no se llega a mostrar el mensaje de busqueda, porque no se termina de cargar la componente (como que no se le agregan los paneles)
Se actualiza una vez que el modelo notifica y ocurre una de dos cosas
* Se cierra el frame
* Se muestra "No hubo resultados"

Pensamos que tal vez era porque el tiempo que kotlin le da a la componente no es suficiente para su inicializacion. Probamos y no encontramos solucion :(

Esperamos pueda ayudarnos a encontrar el problema

Gracias

Saludos!

2021-07-07 02:05 UTC, elagarrigue commented
No se preocupen, es un detalle menor. Terminen con el resto, yo cuando pueda lo veo.

2021-07-07 16:51 UTC, elagarrigue commented
No sé pq se cerró el PR 🤷🏽‍♂️

2021-07-08 12:40 UTC, elagarrigue requested changes
El problema del mensaje que no aparece se soluciona de la siguiente manera. En MoreDetailsController:
```
    override fun open(song: Song){
        moreDetailsView.openView(song)
        Thread {
            moreDetailsModel.searchCard(song.artistName)
        }.start()
    }
```

Ahora, la implementación del pop up escapa a MVC. Debería ser el controller quien maneje el PopUp. 
```
        moreDetailsView.openView(song)
        infoPopUp.openWindow()
        Thread {
            moreDetailsModel.searchCard(song.artistName)
        }.start()
```
Cuando la vista obtenga resultados (o no) le va a tener que avisar al controller, para que el controller actualice el mensaje del pop up, o lo cierre.

- Cuidado con la inversión de dependencias!!!!!

- Actualicen el diagrama

2021-07-08 12:40 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        uiComponents = MoreDetailsUiWindowComponentsImpl()
Inversión de dependencias!

2021-07-08 12:40 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        uiPopUp = MoreDetailsUiPopUpImpl()
Inversión de dependencias!

2021-07-08 12:40 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +            uiPopUp.infoLabel.text = "No hubo resultados"
Smell Feature Envy, no exponer los componentes del pop up

2021-07-09 22:16 UTC, lucasch98 commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        uiComponents = MoreDetailsUiWindowComponentsImpl()
Hola profe, para solucionar la inversión de dependencias pensamos en dos opciones:
- Tener una lista de uiComponents
- Hacer una Factory que nos devuelva instancias de moreDetailsUiComponents

Queríamos saber que opcion es la mejor
Muchas gracias!

2021-07-09 22:36 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/view/MoreDetailsView.kt
> +        uiComponents = MoreDetailsUiWindowComponentsImpl()
factory 👍🏽

2021-07-12 12:04 UTC, elagarrigue requested changes
Lo charlado en el scrum, más una sugerencia extra

2021-07-12 12:04 UTC, elagarrigue commented on JK Hera/src/main/java/ayds/hera/songinfo/moredetails/model/repository/broker/ProxyWikipedia.kt
> +        return card
Se puede simplificar:
```suggestion
       return  try {
            wikipediaService.getArticle(artistName)?.let {
                 mapArticleToCard(it)
            }
        }catch (e: Exception) {
            println("Exception from WikipediaData")
            null
        }
```

2021-07-12 12:53 UTC, elagarrigue approved these changes
🙌🏽

2021-07-12 12:54 UTC, merged